### ISSUE TITLE
What javascript syntax are you using?

### ISSUE THREAD

**Issue by Nicktho** [AlessandroYorba/Despacio#12]

**Comment by AlessandroYorba** [comment]
this: https://github.com/jelera/vim-javascript-syntax

**Comment by Nicktho** [comment]
thanks

**Comment by Nicktho** [comment]
Sorry @AlessandroYorba, were you the one who took the screenshot?

This is me with the theme + syntax, I'm missing a few highlights.

![screen shot 2017-03-21 at 3 04 05 pm](https://cloud.githubusercontent.com/assets/8622243/24132199/c27840be-0e47-11e7-9cc6-69f75e20969b.png)

**Comment by AlessandroYorba** [comment]
@Nicktho Very strange indeed. Looks like the HL colors for "Function, Identifiers, Special, and Operators are missing from your screenshot. However, it looks like the JS syntax plugin did pick up the PreProc highlight "createPositionalPseudo". Here's mine

With Theme and with JS syntax:
![screen shot 2017-03-21 at 12 15 27 pm](https://cloud.githubusercontent.com/assets/11221489/24166338/25ee9a48-0e30-11e7-9405-ce6b7c750c25.png)

Here's a screenshot without JS syntax:
![screen shot 2017-03-21 at 12 17 57 pm](https://cloud.githubusercontent.com/assets/11221489/24166524/c5bcfc72-0e30-11e7-934d-5a19b634a526.png)

BTW, are you using the terminal or gui?

**Comment by Nicktho** [comment]
I'm on the terminal, and using neovim. I might do some digging into highlight groups.

**Comment by AlessandroYorba** [comment]
@Nicktho 

Show me a screenshot of a html file. I wrote despacio so that HTML highlights reference the Function Keyword highlight. So if something is overwriting the highlights that will also tell us. 

Also, from an open JS file and from the vim command line type: 
`highlight Function  ctermfg=223 guifg=#ffdfaf`

If the above command adds the color back to the function keywords that tells me something is overwriting the highlight at runtime

**Comment by Nicktho** [comment]
before `highlight Function ctermfg=223 guifg=#ffdfaf`:

![screen shot 2017-03-22 at 9 14 42 am](https://cloud.githubusercontent.com/assets/8622243/24173405/0ce7d36a-0ee0-11e7-83f2-bcce7bdde8ee.png)

after: 

![screen shot 2017-03-22 at 9 15 39 am](https://cloud.githubusercontent.com/assets/8622243/24173435/3161a036-0ee0-11e7-80c9-efb4583a0d57.png)

html (default syntax)
![screen shot 2017-03-22 at 9 18 07 am](https://cloud.githubusercontent.com/assets/8622243/24173515/7ec98c94-0ee0-11e7-9652-71f6da40018e.png)

**Comment by Nicktho** [comment]
I took the following screenshot from `:h syntax` so it appears the colours are applied correctly to the highlight groups, its just the syntax is not working correctly.

![screen shot 2017-03-22 at 9 38 40 am](https://cloud.githubusercontent.com/assets/8622243/24174180/7150a798-0ee3-11e7-9af6-e3f5b01b6b7c.png)

**Comment by Nicktho** [comment]
Nevermind, calling `syntax enable` after changing the color scheme worked. Thanks for your time Alessandro.

**Comment by AlessandroYorba** [comment]
That's great! Hope you enjoy despacio now!
