### ISSUE TITLE
low-contrast Comment in the darker variants

### ISSUE THREAD

**Issue by tertium** [AlessandroYorba/Despacio#6]
In Twilight and Midnight, comment almost blend with the background, at least for my screen/eyes. In programs, comments are often used for documentation, and so, while differentiated from the normal text, should still be easy to read, imho.

**Comment by AlessandroYorba** [comment]
You're right! I've revised Despacio so that Comments are more visible on all modes. Check out the latest commit

**Comment by tertium** [comment]
Looks great, thank you!
